clone_depth: 1

image:
    - Visual Studio 2015
    - Visual Studio 2017

configuration:
    - Debug
    - Release

platform:
    - x64

before_build:
    - mkdir build
    - cd build
    - cmake ../ -G"MinGW Makefiles"

build_script:
    - mingw32-make
